version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: pizza-postgres
    environment:
      POSTGRES_USER: restaurant_user
      POSTGRES_PASSWORD: restaurant_pass
      POSTGRES_DB: restaurant_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U restaurant_user -d restaurant_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: order-service
    container_name: order-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      CONFIG_PATH: /app/configs/config.yaml
    ports:
      - "3000:3000"
    volumes:
      - ./configs:/app/configs
    command: ["/app/wheres-my-pizza", "--mode=order-service", "--port=3000"]
    restart: unless-stopped

  kitchen-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: kitchen-service
    container_name: kitchen-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      CONFIG_PATH: /app/configs/config.yaml
    volumes:
      - ./configs/config.yaml:/app/configs/config.yaml
    command: ["/app/wheres-my-pizza", "--worker-name=chef_mario", "--order-types=dine_in,takeout", "--prefetch=1"]
    restart: unless-stopped

  tracking-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: tracking-service
    container_name: tracking-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      CONFIG_PATH: /app/configs/config.yaml
    ports:
      - "3002:3002"
    volumes:
      - ./configs/config.yaml:/app/configs/config.yaml
    command: ["/app/wheres-my-pizza", "--mode=tracking-service"]
    restart: unless-stopped

  # notifier-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       SERVICE: notifier-service
  #   container_name: notifier-service
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     CONFIG_PATH: /app/configs/config.yaml
  #   volumes:
  #     - ./configs/config.yaml:/app/configs/config.yaml
  #   command: ["/app/wheres-my-pizza", "--mode=notifier-service"]
  #   restart: unless-stopped

volumes:
  postgres_data:
